---
title: "02_delay_indicator"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(broom)
library(dplyr)
library(splines)
library(purrr)
library(tidyr)
library(sandwich)
library(emmeans)
library(ggplot2)
library(fixest)
library(tidyr)
library(patchwork)
library(scales)
library(kableExtra)
library(stargazer)
library(lme4)
library(broom.mixed)  # For tidying lmer output
library(lmerTest)
library(knitr)
source('~/afc-claire/code/analysis/00_partisan_difference_functions.R')
```

## Data cleaning
```{r}
# outcome is whether a vaccine was received
data = process_data(filename = 'child_politics_covariates_01202026_2018.csv.zip', 
                             time_var = 'time_to_vax', 
                             filter_yr = 1988, 
                             filter_outcome_time= 3+11/12, # must have been vaccinated for an on track second dose
                             filter_engage_time = 1,
                             remove_after_4 = FALSE)
data$indic = as.numeric(data$indic)*100
data$year_num = as.numeric(data$year_num)
```

Children with “on-track” first dose (received MMR vaccine at or after age 12 months and before age 3 years, 11 months)
```{r}
sum(data$indic)/100
```

Plot the disparity in time to delay over time
```{r}
nrow(data)
sum(data$indic/100)
plot_year_disparity(data, outcome = 'indic', 
                    party_baseline = "D", 
                    title = "", 
                    hist_title = "Number of Observations per Year",
                    ylab = "Estimated MMR Vaccination Gap\n(Percentage Points)",
                    line_color = "darkslategray4",
                    hist_color = "darkslategray4",
                    labFalse = "Unvaccinated",
                    labTrue = "Vaccinated",)
ggsave(
  '~/afc-claire/code/figures/mmr_uptake_2018.png',
  width = 7,
  height = 5)

ggsave(
  '~/afc-claire/code/figures/mmr_uptake_2018.pdf',
  width = 7,
  height = 5)
```

Run the interaction model on indicator of delay

```{r}
model_table = interaction_model(data, party_reference = 'D', ref_year = 1988, outcome = 'indic', state_FE = FALSE, x = TRUE)

sum(!is.na(data$svi))
sum(data[!is.na(data$svi), 'indic'])/100
rownames(model_table) <- NULL
# Generate LaTeX table with kable
latex_out <- kable(model_table, 
      format = "latex", 
      caption = "3y11mo indic", 
      booktabs = TRUE,  # For cleaner lines
      align = c("l"),
      escape = FALSE)  # Left-align the first column and right-align others
cat(latex_out)
```


# ON-TIME VACCINATION
```{r}
# outcome is whether a vaccine was received
data = process_data(filename = 'child_politics_covariates_01202026_2018.csv.zip', 
                             time_var = 'time_to_vax', 
                             filter_yr = 1988, 
                             filter_outcome_time= 16/12, # must have been vaccinated for an on time second dose
                             filter_engage_time = 1,
                             remove_after_4 = FALSE)
data$indic = as.numeric(data$indic)*100
data$year_num = as.numeric(data$year_num)
```

Children with “on-schedule” first dose (received MMR vaccine at or after age 12 months and before age 15 months)
```{r}
sum(data$indic)/100
```

```{r}
model_table = interaction_model(data, party_reference = 'D', ref_year = 1988, outcome = 'indic', state_FE = FALSE, x = TRUE)

sum(!is.na(data$svi))
sum(data[!is.na(data$svi), 'indic'])/100
rownames(model_table) <- NULL
# Generate LaTeX table with kable
latex_out <- kable(model_table, 
      format = "latex", 
      caption = "3y11mo indic", 
      booktabs = TRUE,  # For cleaner lines
      align = c("l"),
      escape = FALSE)  # Left-align the first column and right-align others
cat(latex_out)
```

## IN-TIME VACCINATION
```{r}
# outcome is whether a vaccine was received
data = process_data(filename = 'child_politics_covariates_01202026_2018.csv.zip', 
                             time_var = 'time_to_vax', 
                             filter_yr = 1988, 
                             filter_outcome_time= 6+11/12, # must have been vaccinated for an on time second dose
                             filter_engage_time = 1,
                             remove_after_4 = FALSE)
data$indic = as.numeric(data$indic)*100
data$year_num = as.numeric(data$year_num)
```
```{r}
model_table = interaction_model(data, party_reference = 'D', ref_year = 1988, outcome = 'indic', state_FE = FALSE, x = TRUE)

rownames(model_table) <- NULL
sum(!is.na(data$svi))
sum(data[!is.na(data$svi), 'indic'])/100
# Generate LaTeX table with kable
latex_out <- kable(model_table, 
      format = "latex", 
      caption = "3y11mo indic", 
      booktabs = TRUE,  # For cleaner lines
      align = c("l"),
      escape = FALSE)  # Left-align the first column and right-align others
cat(latex_out)
```