---
title: "03_refusal_indicator"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(broom)
library(dplyr)
library(splines)
library(purrr)
library(tidyr)
library(sandwich)
library(emmeans)
library(ggplot2)
library(fixest)
library(tidyr)
library(patchwork)
library(scales)
library(kableExtra)
library(stargazer)
library(lme4)
library(broom.mixed)  # For tidying lmer output
library(lmerTest)
library(knitr)
source('~/afc-claire/code/analysis/00_partisan_difference_functions.R')
```

## Data checking
```{r}
data_count = read_csv(paste0('/share/pi/deho-pi/AFC/mortonc/processed/child_politics_refusals_covariates_01202026_2018.csv.zip'))
data_count$birth_year = as.numeric(substr(data_count$dob, 1, 4))
data_count %>%
  filter(gender != "Other/Unknown" &
         urban_rural != "Unknown" &
           !is.na(svi) &
           STATE != "AK") %>%
  filter(years_to_engage < 1) %>%
  filter(party == "Democratic" | party == "Republican") %>%
  filter(birth_year >= 2000) %>%
  filter(time_to_refusal < Inf) %>%
  nrow()
```


## Data cleaning
```{r}
# outcome is whether a vaccine was received
data = process_data(filename = 'child_politics_refusals_covariates_01202026_2018.csv.zip', 
                    time_var = 'time_to_refusal', 
                    filter_yr = 2000, 
                    filter_outcome_time = 7,
                    filter_engage_time = 1,
                    remove_after_4 = FALSE)

data$indic = as.numeric(data$indic)*100
data$year_num = as.numeric(data$year_num)
```

Children with valid time to refusal (> 0) 
Children with a documented vaccine refusal at or after age 1 year and before age 7 years
```{r}
nrow(data)
sum(data$indic/100)
```

```{r}
# title: "Partisan Gap in Refusal Rate by Birth Year\n(Democrat-Republican)"
plot_year_disparity(data, 
                    party_baseline = "D",
                    outcome = "indic",
                    title = "", 
                    hist_title = "Number of Observations per Year",
                    ylab = "Estimated Gap in Refusal Rate\n(Percentage Points)",
                    labFalse = "No Refusal",
                    labTrue = "Refusal",
                    line_color = 'salmon',
                    hist_color = 'salmon')

ggsave(
  '~/afc-claire/code/figures/refusals_2018.png',
  width = 7,
  height = 5)

ggsave(
  '~/afc-claire/code/figures/refusals_2018.pdf',
  width = 7,
  height = 5)
```

```{r}
model_table = interaction_model(data, party_reference = 'D',
                                ref_year = 2000, outcome = 'indic', 
                                state_FE = FALSE, x = TRUE)

sum(!is.na(data$svi))
sum(data[!is.na(data$svi), 'indic'])/100
rownames(model_table) <- NULL
# Generate LaTeX table with kable
latex_out <- kable(model_table, 
      format = "latex", 
      caption = "Refusal Indicator", 
      booktabs = TRUE,  # For cleaner lines
      align = c("l"),
      escape = FALSE)  # Left-align the first column and right-align others
cat(latex_out)
```