---
title: "04_policy_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(broom)
library(dplyr)
library(splines)
library(purrr)
library(tidyr)
library(sandwich)
library(emmeans)
library(ggplot2)
library(fixest)
library(tidyr)
library(patchwork)
library(scales)
library(kableExtra)
library(stargazer)
library(lme4)
library(broom.mixed)  # For tidying lmer output
library(lmerTest)
library(knitr)
source('~/afc-claire/code/analysis/00_partisan_difference_functions.R')
```

```{r}
# outcome is whether a vaccine was received
data = process_data(filename = 'child_politics_refusals_covariates_01202026.csv.zip', 
                    time_var = 'time_to_refusal', 
                    filter_yr = 2000, 
                    filter_outcome_time = 7,
                    filter_engage_time = 1,
                    remove_after_4 = FALSE)

data$indic = as.numeric(data$indic)*100
data$year_num = as.numeric(data$year_num)
```


```{r}
nrow(data)
sum(data$indic)/100
```

```{r}
source('~/afc-claire/code/analysis/00_partisan_difference_functions.R')

refus_min <- compare_policies(data, 'Minimal')
refus_med <- compare_policies(data, 'Medium')
refus_max <- compare_policies(data, 'Maximal')

sum(!is.na(data$svi))
sum(data[!is.na(data$svi), 'indic'])/100

table = rbind(refus_min, refus_med, refus_max)
colnames(table) = c("Partisan Refusal Gap (95% CI)", "p value")

rownames(table) <- c("No Controls", "+ Regional Controls", "+ Individual Controls")
# Generate LaTeX table with kable
latex_out <- kable(table, 
      format = "latex", 
      caption = "Refusal Indicator", 
      booktabs = TRUE,  # For cleaner lines
      align = c("l"),
      escape = FALSE)  # Left-align the first column and right-align others
cat(latex_out)
```

```{r}
# outcome is whether a vaccine was received
data = process_data(filename = 'child_politics_covariates_01202026.csv.zip', 
                             time_var = 'time_to_vax', 
                             filter_yr = 1988, 
                             filter_outcome_time= 3+11/12, # must have been vaccinated for an on time second dose
                             filter_engage_time = 1,
                             remove_after_4 = FALSE)
data$indic = as.numeric(data$indic)*100
data$year_num = as.numeric(data$year_num)
```

```{r}
nrow(data)
sum(data$indic)/100
```

```{r}
dat_min <- compare_policies(data, 'Minimal')
dat_med <- compare_policies(data, 'Medium')
dat_max <- compare_policies(data, 'Maximal')

sum(!is.na(data$svi))
sum(data[!is.na(data$svi), 'indic'])/100

table = rbind(dat_min, dat_med, dat_max)
colnames(table) = c("Partisan MMR Vaccine Gap (95% CI)", "p value")

rownames(table) <- c("No Controls", "+ Regional Controls", "+ Individual Controls")
# Generate LaTeX table with kable
latex_out <- kable(table, 
      format = "latex", 
      caption = "Refusal Indicator", 
      booktabs = TRUE,  # For cleaner lines
      align = c("l"),
      escape = FALSE)  # Left-align the first column and right-align others
cat(latex_out)
```
